api:
    url : "https://api.met.no/weatherapi/locationforecast/2.0/compact"
    params: {lon : 10.777019, lat : 59.748226}
    headers: {User-Agent : sahatfi@gmail.com}
json_layer1_keys: 
    key1: type 
    key2: geometry 
    key3: properties
json_layer2_keys:
    key1: meta
    key2: timeseries