name: Daily data pipeline
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create config file
        run: |
          mkdir -p config
          cat << EOF > config/config.yaml
          ${{ secrets.CONFIG_YAML }}
          EOF
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        
      - name: Install dependencies
        run: uv sync
          
      - name: Run pipeline
        run: uv run python main.py
          
      - name: Commit database
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/prognoser.db
          git commit -m "Update database $(date +'%Y-%m-%d')" || echo "No changes"
          git push
